"""Codex activity adapter — documented app-server turn events.

Uses ONLY documented Codex app-server protocol surfaces (the schema
bundle generated by ``codex app-server generate-json-schema``):

- server notifications ``turn/started`` and ``turn/completed``, each
  carrying ``{threadId, turn}`` with ``turn.id``, ``turn.status`` and
  timestamps;
- client request ``thread/start``, the documented way to create an
  app-server session Moira owns.

Mapping: ``turn/started`` (status ``inProgress``) starts a session hashed
from the turn id; ``turn/completed`` with status ``completed``/``failed``/
``interrupted`` terminates it. A full ``turn/started`` → ``turn/completed``
sequence is valid only for a thread Moira owns; terminal notifications for
unowned threads are recorded through the completion-notifier surface
(runtime-scoped last event) and can never synthesize RUNNING.

The capability probe runs ``codex app-server --stdio`` with an isolated
``CODEX_HOME`` (no user-state side effects) and reports FULL when a
documented ``thread/start`` succeeds, COMPLETION_ONLY when the protocol is
available but session ownership is not, and UNSUPPORTED otherwise.
"""

from __future__ import annotations

import json
import os
import select
import shutil
import signal
import subprocess
import tempfile
import time
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from . import __version__
from .activity import (
    ActivityEvent,
    ActivityState,
    ActivityStore,
    AgentRuntime,
    LastActivityEvent,
    validate_identity,
)

#: Bounded deadlines for the probe handshake (mirrors the collector).
INIT_DEADLINE_SECONDS = 8
REQUEST_DEADLINE_SECONDS = 10


class CodexCapability(StrEnum):
    FULL = "full"
    COMPLETION_ONLY = "completion_only"
    UNSUPPORTED = "unsupported"


def _send_message(process: subprocess.Popen[str], message: dict[str, object]) -> None:
    if process.stdin is None:
        raise OSError("Codex app-server input unavailable")
    process.stdin.write(json.dumps(message) + "\n")
    process.stdin.flush()


def _read_response(
    process: subprocess.Popen[str],
    request_id: int,
    deadline: float,
) -> dict[str, object]:
    if process.stdout is None:
        raise OSError("Codex app-server output unavailable")
    while time.monotonic() < deadline:
        remaining = max(0.0, deadline - time.monotonic())
        ready, _, _ = select.select([process.stdout], [], [], min(0.25, remaining))
        if not ready:
            continue
        line = process.stdout.readline()
        if not line:
            raise OSError("Codex app-server stopped unexpectedly")
        message = json.loads(line)
        if not isinstance(message, dict):
            raise OSError("Codex app-server response malformed")
        if message.get("id") == request_id:
            return message
    raise TimeoutError("Codex app-server request timed out")


def probe_codex(binary: str = "codex", store: ActivityStore | None = None) -> CodexCapability:
    """Probe the documented app-server protocol with an isolated CODEX_HOME.

    Never touches the user's Codex state: the probe runs against a fresh
    temporary ``CODEX_HOME``. FULL requires a successful documented
    ``thread/start`` (Moira can own an app-server session); a working
    protocol without session ownership is COMPLETION_ONLY; anything else
    is UNSUPPORTED.
    """
    executable = shutil.which(binary)
    if not executable:
        return CodexCapability.UNSUPPORTED
    process: subprocess.Popen[str] | None = None
    try:
        with tempfile.TemporaryDirectory() as temp:
            env = dict(os.environ)
            env["CODEX_HOME"] = temp
            process = subprocess.Popen(
                [executable, "app-server", "--stdio"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                start_new_session=True,
                env=env,
            )
            if process.stdin is None or process.stdout is None:
                raise OSError("Codex app-server pipes unavailable")
            init_deadline = time.monotonic() + INIT_DEADLINE_SECONDS
            _send_message(
                process,
                {
                    "id": 1,
                    "method": "initialize",
                    "params": {"clientInfo": {"name": "moira", "version": __version__}},
                },
            )
            initialized = _read_response(process, 1, init_deadline)
            if "error" in initialized or not isinstance(initialized.get("result"), dict):
                return CodexCapability.UNSUPPORTED
            _send_message(process, {"method": "initialized", "params": {}})
            request_deadline = time.monotonic() + REQUEST_DEADLINE_SECONDS
            _send_message(process, {"id": 2, "method": "thread/start", "params": {}})
            response = _read_response(process, 2, request_deadline)
            if "error" not in response and isinstance(response.get("result"), dict):
                return CodexCapability.FULL
            return CodexCapability.COMPLETION_ONLY
    except (OSError, TimeoutError, subprocess.SubprocessError, json.JSONDecodeError):
        return CodexCapability.UNSUPPORTED
    finally:
        if process is not None and process.poll() is None:
            try:
                os.killpg(process.pid, signal.SIGTERM)
                process.wait(timeout=2)
            except (ProcessLookupError, subprocess.TimeoutExpired):
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    pass


def handle_turn_notification(
    message: dict[str, Any],
    owned_thread_ids: set[str] | frozenset[str],
) -> ActivityEvent | LastActivityEvent | None:
    """Map one documented turn notification to a typed activity event.

    - ``turn/started`` with ``turn.status == "inProgress"`` yields a
      RUNNING session event — valid only for an owned thread; for unowned
      threads it is ignored (never synthesized).
    - ``turn/completed`` with a terminal status yields the matching
      terminal event: a session-scoped event for owned threads, a
      completion-only last event for unowned threads.
    - Malformed or unrelated messages yield None (silent ignore).
    """
    if not isinstance(message, dict):
        return None
    method = message.get("method")
    if method not in ("turn/started", "turn/completed"):
        return None
    params = message.get("params")
    if not isinstance(params, dict):
        return None
    thread_id = params.get("threadId")
    turn = params.get("turn")
    if not isinstance(thread_id, str) or not thread_id.strip() or not isinstance(turn, dict):
        return None
    turn_id = turn.get("id")
    status = turn.get("status")
    if not isinstance(turn_id, str) or not turn_id.strip() or not isinstance(status, str):
        return None
    try:
        session_hash = validate_identity(turn_id)
    except ValueError:
        return None
    now = datetime.now(UTC)
    owned = thread_id in owned_thread_ids
    if method == "turn/started":
        if status != "inProgress" or not owned:
            return None
        return ActivityEvent(
            runtime=AgentRuntime.CODEX,
            state=ActivityState.RUNNING,
            session_hash=session_hash,
            model="",
            at=now,
        )
    terminal = {
        "completed": ActivityState.COMPLETED,
        "failed": ActivityState.FAILED,
        "interrupted": ActivityState.INTERRUPTED,
    }.get(status)
    if terminal is None:
        return None
    if owned:
        return ActivityEvent(
            runtime=AgentRuntime.CODEX,
            state=terminal,
            session_hash=session_hash,
            model="",
            at=now,
        )
    return LastActivityEvent(
        runtime=AgentRuntime.CODEX,
        state=terminal,
        model="",
        at=now,
    )


def record_turn_notification(
    message: dict[str, Any],
    owned_thread_ids: set[str] | frozenset[str],
    store: ActivityStore,
) -> bool:
    """Apply one documented turn notification to the store.

    Returns True when an event was recorded (accepted or idempotent
    replay). Failures are silent — the agent is never affected.
    """
    event = handle_turn_notification(message, owned_thread_ids)
    if event is None:
        return False
    try:
        if isinstance(event, ActivityEvent):
            store.record(event)
        else:
            store.record_last(event)
    except (ValueError, OSError):
        return False
    return True
