"""Codex activity adapter — documented app-server turn events.

Uses ONLY documented Codex app-server protocol surfaces (the schema
bundle generated by ``codex app-server generate-json-schema``):

- server notifications ``turn/started`` and ``turn/completed``, each
  carrying ``{threadId, turn}`` with ``turn.id`` (UUIDv7), ``turn.status``
  and timestamps;
- client requests ``thread/start`` (the documented way to create an
  app-server session Moira owns) and ``turn/start`` (drives a real turn:
  ``input`` is an array of ``{type: "text", text}`` items).

Mapping: ``turn/started`` (status ``inProgress``) starts a turn in the
session hashed from the owning ``threadId``; ``turn/completed`` with
status ``completed``/``failed``/``interrupted`` terminates it. A full
``turn/started`` → ``turn/completed`` sequence is valid only for a thread
Moira owns; terminal notifications for unowned threads are recorded
through the completion-notifier surface (runtime-scoped last event) and
can never synthesize RUNNING.

Supported capability (honest, reduced): Moira can own an app-server
session through the documented stdio protocol, drive real turns through
``turn/start`` and continuously consume the real ``turn/started`` and
``turn/completed`` notifications for the threads it owns. Codex does NOT
document a way for a third party to observe turns from ordinary
independent CLI sessions: turn notifications are delivered only to the
client subscribed to the thread (the interactive TUI attaches to the
app-server daemon socket it owns). The capability probe therefore reports
SESSION_OWNED (Moira-owned app-server sessions), COMPLETION_ONLY or
UNSUPPORTED — never "full live monitoring".

``CodexSession`` is the production lifecycle: it starts the app-server
through the documented protocol, tracks the owned ``threadId`` values,
consumes real notifications into an ``ActivityStore``, terminates
cleanly, and is bounded in time and resources. Capability tests always
run with an isolated ``CODEX_HOME`` so the user's Codex state is never
modified.
"""

from __future__ import annotations

import json
import os
import select
import shutil
import signal
import subprocess
import tempfile
import time
from collections.abc import Iterator
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from . import __version__
from .activity import (
    ActivityEvent,
    ActivityState,
    ActivityStore,
    AgentRuntime,
    LastActivityEvent,
    composite_identity,
    validate_identity,
)

#: Bounded deadlines for the probe and session handshakes.
INIT_DEADLINE_SECONDS = 8
REQUEST_DEADLINE_SECONDS = 10

#: Bounded deadline for one real turn's notifications (the auth-less
#: verification turn fails fast; a real turn is bounded the same way).
TURN_DEADLINE_SECONDS = 30.0


class CodexCapability(StrEnum):
    SESSION_OWNED = "session_owned"
    COMPLETION_ONLY = "completion_only"
    UNSUPPORTED = "unsupported"


class CodexSessionError(RuntimeError):
    """Bounded fail-closed outcome for a Codex app-server session."""


def _send_message(process: subprocess.Popen[str], message: dict[str, object]) -> None:
    if process.stdin is None:
        raise OSError("Codex app-server input unavailable")
    process.stdin.write(json.dumps(message) + "\n")
    process.stdin.flush()


def _read_response(
    process: subprocess.Popen[str],
    request_id: int,
    deadline: float,
) -> dict[str, object]:
    if process.stdout is None:
        raise OSError("Codex app-server output unavailable")
    while time.monotonic() < deadline:
        remaining = max(0.0, deadline - time.monotonic())
        ready, _, _ = select.select([process.stdout], [], [], min(0.25, remaining))
        if not ready:
            continue
        line = process.stdout.readline()
        if not line:
            raise OSError("Codex app-server stopped unexpectedly")
        message = json.loads(line)
        if not isinstance(message, dict):
            raise OSError("Codex app-server response malformed")
        if message.get("id") == request_id:
            return message
    raise TimeoutError("Codex app-server request timed out")


def _reap(process: subprocess.Popen[Any] | None) -> None:
    """Terminate the app-server process group cleanly (bounded, idempotent)."""
    if process is None or process.poll() is not None:
        return
    try:
        os.killpg(process.pid, signal.SIGTERM)
        process.wait(timeout=2)
    except (ProcessLookupError, subprocess.TimeoutExpired):
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        try:
            process.wait(timeout=2)
        except subprocess.TimeoutExpired:
            pass


def probe_codex(binary: str = "codex", store: ActivityStore | None = None) -> CodexCapability:
    """Probe the documented app-server protocol with an isolated CODEX_HOME.

    Never touches the user's Codex state: the probe runs against a fresh
    temporary ``CODEX_HOME``. SESSION_OWNED requires a successful
    documented ``thread/start`` (Moira can own an app-server session and
    receive its real turn events); a working protocol without session
    ownership is COMPLETION_ONLY; anything else is UNSUPPORTED.
    """
    executable = shutil.which(binary)
    if not executable:
        return CodexCapability.UNSUPPORTED
    process: subprocess.Popen[str] | None = None
    try:
        with tempfile.TemporaryDirectory() as temp:
            env = dict(os.environ)
            env["CODEX_HOME"] = temp
            process = subprocess.Popen(
                [executable, "app-server", "--stdio"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                start_new_session=True,
                env=env,
            )
            if process.stdin is None or process.stdout is None:
                raise OSError("Codex app-server pipes unavailable")
            init_deadline = time.monotonic() + INIT_DEADLINE_SECONDS
            _send_message(
                process,
                {
                    "id": 1,
                    "method": "initialize",
                    "params": {"clientInfo": {"name": "moira", "version": __version__}},
                },
            )
            initialized = _read_response(process, 1, init_deadline)
            if "error" in initialized or not isinstance(initialized.get("result"), dict):
                return CodexCapability.UNSUPPORTED
            _send_message(process, {"method": "initialized", "params": {}})
            request_deadline = time.monotonic() + REQUEST_DEADLINE_SECONDS
            _send_message(process, {"id": 2, "method": "thread/start", "params": {}})
            response = _read_response(process, 2, request_deadline)
            if "error" not in response and isinstance(response.get("result"), dict):
                return CodexCapability.SESSION_OWNED
            return CodexCapability.COMPLETION_ONLY
    except (OSError, TimeoutError, subprocess.SubprocessError, json.JSONDecodeError):
        return CodexCapability.UNSUPPORTED
    finally:
        _reap(process)


def handle_turn_notification(
    message: dict[str, Any],
    owned_thread_ids: set[str] | frozenset[str],
) -> ActivityEvent | LastActivityEvent | None:
    """Map one documented turn notification to a typed activity event.

    Session identity is the owning thread; the turn identity binds the
    turn to its thread (hashed composite), so multiple turns per thread
    stay distinguishable and hashed.

    - ``turn/started`` with ``turn.status == "inProgress"`` yields a
      RUNNING turn event — valid only for an owned thread; for unowned
      threads it is ignored (never synthesized).
    - ``turn/completed`` with a terminal status yields the matching
      terminal event: a turn-scoped event for owned threads, a
      completion-only last event for unowned threads.
    - Malformed or unrelated messages yield None (silent ignore).
    """
    if not isinstance(message, dict):
        return None
    method = message.get("method")
    if method not in ("turn/started", "turn/completed"):
        return None
    params = message.get("params")
    if not isinstance(params, dict):
        return None
    thread_id = params.get("threadId")
    turn = params.get("turn")
    if not isinstance(thread_id, str) or not thread_id.strip() or not isinstance(turn, dict):
        return None
    turn_id = turn.get("id")
    status = turn.get("status")
    if not isinstance(turn_id, str) or not turn_id.strip() or not isinstance(status, str):
        return None
    try:
        session_hash = validate_identity(thread_id)
    except ValueError:
        return None
    turn_hash = composite_identity(thread_id, turn_id)
    if turn_hash is None:
        return None
    now = datetime.now(UTC)
    owned = thread_id in owned_thread_ids
    if method == "turn/started":
        if status != "inProgress" or not owned:
            return None
        return ActivityEvent(
            runtime=AgentRuntime.CODEX,
            state=ActivityState.RUNNING,
            session_hash=session_hash,
            turn_hash=turn_hash,
            model="",
            at=now,
        )
    terminal = {
        "completed": ActivityState.COMPLETED,
        "failed": ActivityState.FAILED,
        "interrupted": ActivityState.INTERRUPTED,
    }.get(status)
    if terminal is None:
        return None
    if owned:
        return ActivityEvent(
            runtime=AgentRuntime.CODEX,
            state=terminal,
            session_hash=session_hash,
            turn_hash=turn_hash,
            model="",
            at=now,
        )
    return LastActivityEvent(
        runtime=AgentRuntime.CODEX,
        state=terminal,
        model="",
        at=now,
    )


def record_turn_notification(
    message: dict[str, Any],
    owned_thread_ids: set[str] | frozenset[str],
    store: ActivityStore,
) -> bool:
    """Apply one documented turn notification to the store.

    Returns True when an event was recorded (accepted or idempotent
    replay). Failures are silent — the agent is never affected.
    """
    event = handle_turn_notification(message, owned_thread_ids)
    if event is None:
        return False
    try:
        if isinstance(event, ActivityEvent):
            store.record(event)
        else:
            store.record_last(event)
    except (ValueError, OSError):
        return False
    return True


class _LineReader:
    """Select-safe line reader over a binary-mode pipe.

    ``select`` on a ``TextIOWrapper`` stalls when the text layer has
    already buffered several lines (the OS pipe is momentarily empty), so
    the session reads raw bytes from the descriptor and splits lines
    itself.
    """

    def __init__(self, stream: Any) -> None:
        self._fd = stream.fileno()
        self._pending = b""

    def lines(self, deadline: float) -> Iterator[str]:
        while time.monotonic() < deadline:
            remaining = max(0.0, deadline - time.monotonic())
            ready, _, _ = select.select([self._fd], [], [], min(0.25, remaining))
            if not ready:
                continue
            chunk = os.read(self._fd, 65536)
            if not chunk:
                raise OSError("Codex app-server stopped unexpectedly")
            self._pending += chunk
            while b"\n" in self._pending:
                line, self._pending = self._pending.split(b"\n", 1)
                yield line.decode("utf-8", "replace")


class CodexSession:
    """One Moira-owned app-server session (documented stdio protocol).

    Production lifecycle: starts ``codex app-server --stdio``, completes
    the initialize handshake, owns a thread through ``thread/start``,
    drives real turns through ``turn/start`` and continuously consumes
    the real ``turn/started``/``turn/completed`` notifications into an
    ``ActivityStore``. Terminates cleanly (process-group SIGTERM then
    SIGKILL fallback, idempotent) and is bounded in time and resources.

    Capability tests always use an isolated ``CODEX_HOME`` (the default),
    so the user's Codex state is never modified.
    """

    def __init__(
        self,
        store: ActivityStore,
        binary: str = "codex",
        codex_home: Path | None = None,
    ) -> None:
        self._store = store
        self._binary = binary
        self._temp_home: tempfile.TemporaryDirectory[str] | None = None
        if codex_home is None:
            self._temp_home = tempfile.TemporaryDirectory(prefix="moira-codex-")
            self.codex_home = Path(self._temp_home.name)
        else:
            self.codex_home = codex_home
        self._process: subprocess.Popen[bytes] | None = None
        self._reader: _LineReader | None = None
        self._owned_threads: set[str] = set()
        self._closed = False

    def __enter__(self) -> CodexSession:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    def _write(self, message: dict[str, object]) -> None:
        process = self._process
        if process is None or process.stdin is None:
            raise CodexSessionError("Codex app-server input unavailable")
        process.stdin.write(json.dumps(message).encode("utf-8") + b"\n")
        process.stdin.flush()

    def _read_response(self, request_id: int, deadline: float) -> dict[str, object]:
        reader = self._reader
        if reader is None:
            raise CodexSessionError("Codex app-server output unavailable")
        for line in reader.lines(deadline):
            try:
                message = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(message, dict):
                continue
            if message.get("id") == request_id:
                return message
        raise TimeoutError("Codex app-server request timed out")

    def start(self) -> str:
        """Start the app-server and own one thread; returns the thread id."""
        executable = shutil.which(self._binary)
        if not executable:
            raise CodexSessionError("Codex CLI is not installed")
        self.codex_home.mkdir(parents=True, exist_ok=True)
        env = dict(os.environ)
        env["CODEX_HOME"] = str(self.codex_home)
        process = subprocess.Popen(
            [executable, "app-server", "--stdio"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
            env=env,
        )
        self._process = process
        self._reader = _LineReader(process.stdout)
        try:
            if process.stdin is None or process.stdout is None:
                raise CodexSessionError("Codex app-server pipes unavailable")
            init_deadline = time.monotonic() + INIT_DEADLINE_SECONDS
            self._write(
                {
                    "id": 1,
                    "method": "initialize",
                    "params": {"clientInfo": {"name": "moira", "version": __version__}},
                }
            )
            initialized = self._read_response(1, init_deadline)
            if "error" in initialized or not isinstance(initialized.get("result"), dict):
                raise CodexSessionError("Codex app-server initialize failed")
            self._write({"method": "initialized", "params": {}})
            request_deadline = time.monotonic() + REQUEST_DEADLINE_SECONDS
            self._write({"id": 2, "method": "thread/start", "params": {}})
            response = self._read_response(2, request_deadline)
            result = response.get("result")
            thread = result.get("thread") if isinstance(result, dict) else None
            thread_id = thread.get("id") if isinstance(thread, dict) else None
            if not isinstance(thread_id, str) or not thread_id.strip():
                raise CodexSessionError("Codex app-server thread/start failed")
            self._owned_threads.add(thread_id)
            return thread_id
        except (OSError, TimeoutError, json.JSONDecodeError) as exc:
            self.close()
            raise CodexSessionError(str(exc)) from exc

    def run_turn(self, text: str, deadline: float = TURN_DEADLINE_SECONDS) -> ActivityState:
        """Drive one real turn and consume its real notifications.

        Sends the documented ``turn/start`` request (``input`` items) for
        the owned thread and consumes the stream until a real
        ``turn/completed`` notification for an owned thread arrives (or
        the bounded deadline). Every real ``turn/started``/``turn/completed``
        notification is recorded through the ActivityStore. Returns the
        terminal state; raises TimeoutError when the deadline is exceeded
        and CodexSessionError on protocol failures.
        """
        process = self._process
        reader = self._reader
        if process is None or reader is None:
            raise CodexSessionError("Codex app-server session is not started")
        thread_id = next(iter(self._owned_threads), None)
        if thread_id is None:
            raise CodexSessionError("Codex app-server session owns no thread")
        self._write(
            {
                "id": 3,
                "method": "turn/start",
                "params": {"threadId": thread_id, "input": [{"type": "text", "text": text}]},
            }
        )
        # Consume the stream: responses are skipped, real notifications are
        # recorded; stop at the owned thread's turn/completed or the bound.
        end = time.monotonic() + deadline
        for line in reader.lines(end):
            try:
                message = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(message, dict):
                continue
            if message.get("method") == "turn/completed":
                params = message.get("params")
                turn = params.get("turn") if isinstance(params, dict) else None
                status = turn.get("status") if isinstance(turn, dict) else None
                terminal = (
                    {
                        "completed": ActivityState.COMPLETED,
                        "failed": ActivityState.FAILED,
                        "interrupted": ActivityState.INTERRUPTED,
                    }.get(status)
                    if isinstance(status, str)
                    else None
                )
                if isinstance(params, dict) and params.get("threadId") in self._owned_threads:
                    record_turn_notification(message, self._owned_threads, self._store)
                    if terminal is not None:
                        return terminal
                    raise CodexSessionError("Codex turn/completed carries no terminal status")
            record_turn_notification(message, self._owned_threads, self._store)
        raise TimeoutError("Codex turn did not complete within the bounded deadline")

    def close(self) -> None:
        """Terminate the app-server cleanly and release resources
        (idempotent; safe to call after any failure)."""
        if self._closed:
            return
        self._closed = True
        _reap(self._process)
        self._process = None
        self._reader = None
        if self._temp_home is not None:
            try:
                self._temp_home.cleanup()
            except OSError:
                pass
            self._temp_home = None
