#!/bin/sh
# Package 7r Lintian gate (acceptance criteria 7-9).
#
# Runs Lintian against the repository's own .deb in a PINNED DISPOSABLE
# container and requires ZERO tags at EVERY display/failure level
# (error, warning, info, pedantic, experimental). "An unavailable local
# command is not a passing Debian gate" — the gate does not depend on a
# host lintian install; the environment is pinned IMMUTABLY:
#
#   - image: debian:bookworm-slim pinned by DIGEST
#     (debian@sha256:abd67ffcfa541b485a3dff59865ab629aa048a6c613e639d36e7456b0b229241)
#   - package: lintian=2.116.3+deb12u1 (EXACT apt version, not unversioned)
#   - the gate FAILS on any image/package/version mismatch.
#
# Lintian is invoked with explicit display/failure settings for every
# tag level (defaults are forbidden):
#
#   lintian -E -I --pedantic \
#     --fail-on error,warning,info,pedantic,experimental <deb>
#
#   -E           display experimental "X:" tags (normally suppressed)
#   -I           display info "I:" tags (normally suppressed)
#   --pedantic   display pedantic "P:" tags (normally suppressed)
#   --fail-on    exit 2 when ANY tag at any of those levels is emitted
#
# The package itself reaches zero tags through the committed md5sums
# generation and the committed justified override in build-deb.sh /
# packaging/lintian-overrides.
#
# Deterministic self-test (`--self-test`): builds a fixture package
# whose Description synopsis ends with a period — a tag that DEFAULT
# lintian hides ("synopsis-is-a-sentence", info) — and proves the
# full-display invocation surfaces it AND fails the gate. Reproducible
# from committed files: the fixture is GENERATED by this script (no
# binaries are committed) and the mount directory lives under the
# repository (snap-docker bind mounts from /tmp appear empty).
#
# Usage:
#   ./scripts/lintian-gate.sh            # gate the repository's own deb
#   ./scripts/lintian-gate.sh --self-test
#   DOCKER=... ./scripts/lintian-gate.sh
#   sg docker -c './scripts/lintian-gate.sh'
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
docker_cmd=${DOCKER:-docker}

# ── Immutable pins (the gate fails on any mismatch) ─────────────────────────
# Digest of debian:bookworm-slim at gate authoring time; docker refuses to
# run anything else. The exact lintian version is enforced both by the
# pinned apt-get install and by the exact version check below.
image="debian@sha256:abd67ffcfa541b485a3dff59865ab629aa048a6c613e639d36e7456b0b229241"
image_tag="debian:bookworm-slim"
lintian_version="2.116.3+deb12u1"

# Explicit display/failure settings for EVERY tag level (defaults are
# forbidden by the gate contract).
lintian_flags="-E -I --pedantic --fail-on error,warning,info,pedantic,experimental"

# Pinned build epoch: identical source + identical SOURCE_DATE_EPOCH →
# byte-identical .deb (same value as the reproducibility gate).
source_date_epoch="${SOURCE_DATE_EPOCH:-1754380800}"

version=$(sed -n 's/^__version__ = "\([^"]*\)"$/\1/p' "$project_dir/src/moira/__init__.py")
case "$version" in
  [0-9]*.[0-9]*.[0-9]*)
    ;;
  *)
    echo "lintian-gate: cannot derive a valid version from src/moira/__init__.py" >&2
    exit 1
    ;;
esac

deb="$project_dir/dist/moira_${version}_all.deb"
mount_dir="$project_dir/dist/.lintian"
log="$project_dir/dist/lintian.log"

container_lintian() {
  # Run lintian inside the pinned disposable container; stdout carries the
  # full-display lintian output. $1 = the .deb file name inside the /deb
  # mount (host-controlled: "moira.deb" or "fixture.deb").
  _target="$1"
  "$docker_cmd" run --rm \
    -v "$mount_dir:/deb:ro" \
    "$image" sh -c "
      apt-get update -qq >/dev/null 2>&1 &&
      apt-get install -y -qq --no-install-recommends 'lintian=$lintian_version' >/dev/null 2>&1 &&
      lintian --version &&
      lintian $lintian_flags /deb/$_target" 2>&1 || true
}

check_version() {
  # Exact version match — the log's first line must be the pinned version.
  grep -qx "Lintian v$lintian_version" "$log" || {
    echo "lintian-gate: FAILED — lintian version mismatch (expected Lintian v$lintian_version)" >&2
    exit 1
  }
}

if [ "${1:-}" = "--self-test" ]; then
  fixture="$project_dir/dist/.lintian-selftest"
  rm -rf "$fixture"
  mkdir -p "$fixture/DEBIAN" "$fixture/usr/share/doc/lintian-selftest"
  # Deterministic hidden tag: a Description synopsis ending with a period
  # fires "synopsis-is-a-sentence" (info) — hidden by DEFAULT lintian.
  cat > "$fixture/DEBIAN/control" <<'CTRL'
Package: lintian-selftest
Version: 1.0
Section: misc
Priority: optional
Architecture: all
Maintainer: Moira Gate <gate@example.invalid>
Description: Package fixture synopsis ending with a period.
 The long description is long enough to avoid length warnings
 and exists only to make the fixture structurally valid.
CTRL
  printf 'lintian-selftest (1.0) unstable; urgency=low\n\n  * fixture.\n\n -- Moira Gate <gate@example.invalid>  Mon, 01 Jan 2024 00:00:00 +0000\n' \
    > "$fixture/usr/share/doc/lintian-selftest/changelog"
  gzip -n -9 -c "$fixture/usr/share/doc/lintian-selftest/changelog" \
    > "$fixture/usr/share/doc/lintian-selftest/changelog.gz"
  rm "$fixture/usr/share/doc/lintian-selftest/changelog"
  printf 'Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/\nUpstream-Name: lintian-selftest\nFiles: *\nCopyright: 2024 Moira Gate\nLicense: MIT\n Permission is hereby granted, free of charge.\n' \
    > "$fixture/usr/share/doc/lintian-selftest/copyright"
  (
    cd "$fixture" &&
      find usr -type f -print0 | sort -z | xargs -0 md5sum | sed 's|  \./|  |' > DEBIAN/md5sums
  )
  find "$fixture" -type d -exec chmod 0755 {} +
  find "$fixture" -type f -exec chmod 0644 {} +
  dpkg-deb --build --root-owner-group -Zxz -z9 "$fixture" "$fixture/fixture.deb" >/dev/null

  rm -rf "$mount_dir"
  mkdir -p "$mount_dir"
  cp "$fixture/fixture.deb" "$mount_dir/fixture.deb"
  echo "lintian-gate: running self-test in pinned image $image_tag"
  container_lintian "fixture.deb" > "$log" 2>&1
  check_version
  if grep -Eq '^[EWIPX]: ' "$log"; then
    hidden=$(grep -E '^[IPX]: ' "$log" | head -1 || true)
    echo "lintian-gate: SELF-TEST PASS — hidden tags surface and fail the gate: $hidden"
    rm -rf "$mount_dir" "$fixture"
    exit 0
  fi
  echo "lintian-gate: SELF-TEST FAILED — no tag was emitted for the fixture" >&2
  rm -rf "$mount_dir" "$fixture"
  exit 1
fi

echo "lintian-gate: building $deb (SOURCE_DATE_EPOCH=$source_date_epoch)"
SOURCE_DATE_EPOCH="$source_date_epoch" MOIRA_OUTPUT_DIR="$project_dir/dist" \
  "$project_dir/scripts/build-deb.sh" >/dev/null
[ -f "$deb" ] || {
  echo "lintian-gate: build produced no .deb at $deb" >&2
  exit 1
}

rm -rf "$mount_dir"
mkdir -p "$mount_dir"
cp "$deb" "$mount_dir/moira.deb"

echo "lintian-gate: running lintian in pinned image $image_tag"
container_lintian "moira.deb" > "$log" 2>&1
check_version

echo "----- lintian.log -----"
cat "$log"
echo "-----------------------"

if grep -Eq '^[EWIPX]: ' "$log"; then
  echo "lintian-gate: FAILED — lintian reported tags (zero tags at every level required)" >&2
  exit 1
fi

echo "lintian-gate: PASS — zero lintian tags (lintian $lintian_version, image $image_tag)"
rm -rf "$mount_dir"
